name: terraform-docs

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  docs-storage-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

      - name: Render docs for modules/storage
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: modules/storage
          output-file: README.md
          output-method: inject
          git-push: "true"

  docs-root:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

      - name: Render docs for root module
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
